<?php echo $this->doctype() ;
$this ->layout()->userPanel = $this -> action('panel','user');
?>

<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <title>vEagleFly的博客</title>
   <link rel = 'stylesheet' href = '/css/style.css' type = 'text/css'>
     
   </head>
<body>
<div id = 'Home'>
<?php
//echo $this ->layout()->userPanel;
echo $this->partial('head.phtml') ?>
<div class = 'content'>
    <div class = 'aside'>
       
    
   <?php echo $this->partial('aside.phtml') ?>  
    </div>
    <div class = 'right'>
        <?php echo $this->layout()->content ?>
    </div>

</div>

<?php 
 
echo $this->partial('foot.phtml') ?>
</div>
</body>
</html>
